# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XqgL-2E5GM8_ZGk8LTZJWm7vGWHFmfy
"""

from .game_function import(
    initialize_grid,
    print_grid,
    add_new,
    move_left,
    move_right,
    move_up,
    move_down,
    check_win,
    check_lose
)