# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145F6lOBTycoRH8JK-xNmQMv2I1CcdLqw
"""

import game_functions as gf

def main():
    grid = gf.initialize_grid()
    while True:
        gf.display_grid(grid)
        move = input("Enter move (w/a/s/d): ").strip().lower()
        if move == 'a':
            gf.move_left(grid)
        elif move == 'd':
            gf.move_right(grid)
        elif move == 'w':
            gf.move_up(grid)
        elif move == 's':
            gf.move_down(grid)
        else:
            print("Invalid input! Use w, a, s, or d.")
            continue
        gf.add_random_tile(grid)  # Add a new '2' tile after each move

main()